apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: ${TIMESCALE_DB}
    user: ${TIMESCALE_USER}
    secureJsonData:
      password: ${TIMESCALE_PASSWORD}
    jsonData:
      postgresVersion: 1600
      sslmode: disable
      timescaledb: true
    isDefault: true
    editable: false
