apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: base
    user: admin
    secureJsonData:
      password: password
    jsonData:
      postgresVersion: 1600
      sslmode: disable
      timescaledb: true
    isDefault: true
    editable: true
