services:
  streaming-consumer-timescaledb-dashboard:
    image: thesis-pipeline:latest
    container_name: "streaming.consumer.timescaledb.dashboard"
    command: python -m src.streaming.consumer.timescaledb.dashboard.run
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
      TZ: UTC
      TIMESCALEDB_KAFKA_AUTO_OFFSET_RESET: earliest
      TIMESCALEDB_KAFKA_MIN_WARMUP_MESSAGES: 500
      TIMESCALE_HOST: timescaledb
      TIMESCALE_PORT: 5432
      TIMESCALE_DB: base
      TIMESCALE_USER: admin
      TIMESCALE_PASSWORD: password
    volumes:
      - ../src:/app/src
    restart: unless-stopped

networks:
  default:
    name: streaming
    driver: bridge
    external: true
