services:
  streaming-producer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: "streaming.producer"
    command: python /app/src/streaming/producer/run.py
    environment:
      PYTHONUNBUFFERED: 1
      SYMBOL: BTCUSDT
      BOOTSTRAP_SERVERS: redpanda:9092
      TZ: UTC
    volumes:
      - ../src:/app/src
    restart: unless-stopped

networks:
  default:
    name: streaming
    driver: bridge
    external: true
