services:
  streaming-consumer-minio-binance:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: "streaming.consumer.minio.binance"
    command: python -m src.streaming.consumer.minio.binance.run
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
      TZ: UTC
    volumes:
      - ../src:/app/src
    restart: unless-stopped

  streaming-consumer-minio-reddit:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: "streaming.consumer.minio.reddit"
    command: python -m src.streaming.consumer.minio.reddit.run
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
      TZ: UTC
    volumes:
      - ../src:/app/src
    restart: unless-stopped

networks:
  default:
    name: streaming
    driver: bridge
    external: true
